# Generated by Django 5.0.4 on 2024-05-06 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=200)),
                ('año_publi', models.PositiveIntegerField()),
                ('stock', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('rol', models.CharField(choices=[('usuario regular', 'Usuario Regular'), ('administrador', 'Administrador')], max_length=20)),
                ('libros_prestados', models.ManyToManyField(related_name='usuarios_prestados', to='biblioteca.libro')),
            ],
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
