# Generated by Django 5.0.4 on 2024-05-06 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_libro_usuario_delete_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='password',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
